### ISSUE TITLE
【特性】能在保存文件的时候自动更新"Last Modified"条目吗？

### ISSUE THREAD

**Issue by yecharlie** [nine2/vim-copyright#3]
作者你好，请问是不是能在保存的时候自动调用CopyRightUpdate方法，从而更新Last Modified项目呢？
这项功能暂时不能通过autocmd隐式调用CopyRightUpdate来简单实现，因为目前显示调用CopyRightUpdate在检测不到已有头时会插入新的文件头，而在隐式调用的时候我想人们通常会希望在没有文件头的时候就忽略更新。

**Comment by bbxytl** [comment]
Hi,
目前已经支持了此功能。

```
" auto update copyright when save file. Default: 1; 0:close auto.
let g:file_copyright_auto_update = 1
```

同时支持了自定义 copyright。

```
let g:file_copyright_company = "your company, default: null"
let g:file_copyright_rights = "custom_rights, default:'All rights reserved.'"
```

**Comment by yecharlie** [comment]
下午又试了一个办法，把Vim终端退出重开就可以了。文字就留在这里给别人提个醒吧。
----------------------------------------------------------------------------
嗨！
我尝试了一下，还是更新不了，不知道是哪里出了问题。
首先我使用Vundle更新插件，通过更新日志确认插件在该途径下已经是所能获取到的最新版本，同时保证以下测试都在不同的时间（分钟级）下进行：
- 在一个已经生成文件头的文件里，使用保存。
- 对该文件做实质性改动，保存。

另外我还尝试了：
- 在.vimrc中添加 let g:file_copyright_auto_update = 1，并更新.vimrc
