### ISSUE TITLE
Custom copyright text support

### ISSUE THREAD

**Issue by PezCoder** [nine2/vim-copyright#4]
The plugin works amazing out of the box, thank you for this.

Actually, in my use case we use a specific copyright format which I wanted to use is:

```
// Copyright (c) 2020 MyCompany All Rights Reserved
```

I noticed that the copyright format is pretty much hardcoded [code reference](https://github.com/nine2/vim-copyright/blob/master/plugin/copyright.vim#L110-L117)

Is there a possibility to make this generic & let this be defined through the config instead?

**Comment by bbxytl** [comment]
Hi,
Already supports this feature.

```
let g:file_copyright_company = "your company, default: null"
let g:file_copyright_rights = "custom_rights, default:'All rights reserved.'"
```

And the automatic update feature is supported!

```
" auto update copyright when save file. Default: 1; 0:close auto.
let g:file_copyright_auto_update = 1
```

**Comment by PezCoder** [comment]
@bbxytl Thank you for the response. Probably I wasn't very clear with my question, let me try rephrasing it.

At the moment, there are options to configure copyright company & rights like you mentioned & those are wonderful.
But the existing format that copyright comes in is standard which is:

```
# ====================================================
#   Copyright (C) 2018 All rights reserved.
#
#   Author        : your name
#   Email         : your email
#   File Name     : eg.py
#   Last Modified : 2018-04-06 14:27
#   Describe      :
#
# ====================================================
```

But for our organization, we follow a simple copyright statement which looks as simple as 
```
// Copyright (c) 2020 MyCompany All Rights Reserved
```

Notice it doesn't have any author, email, file name, last modified etc.

My ask was is it possible to achieve the format I mentioned through the plugin, i.e let the user define a custom format?
