### ISSUE TITLE
【优化】当前在自动保存时会连带移动光标到上次修改的位置（即日期位置）

### ISSUE THREAD

**Issue by yecharlie** [nine2/vim-copyright#5]
你好，开发者！
我又来了。
如题，一般用户都是边写边保存的（而不是全部写完再保存退出），这种跳转其实很影响体验（它会打断思路），可以考虑优化一下，消除其副作用，达到一种“静默更新”的效果。

**Comment by bbxytl** [comment]
已支持此功能
